### ISSUE TITLE
List of Items goes offscreen.

### ISSUE THREAD

**Issue by somethingjohn** [dagochen/RABuff#2]
Hi, first of all thank you for the great work you did on this addon.
I was glad to see the addition of so many potions/items. When I try to add a query for an item though, this long list goes on beyond the upper border of my screen and I cant seem to be able to move the RABuffs settings menu to be able to see them all.
I would appreciate any help you could offer.

Update: I was able to move it by using the MoveAnything addon, and the /move DropDownList2 command. Not ideal and gave some errors but it worked.

**Comment by dagochen** [comment]
My advice would have been to buy a new display ;) I know about this problem but wont change anything anymore.

**Comment by Mfoor** [comment]
i have a 1920x1080 display. The item buffs window grows upward and not down as all the others do. This should be relativity easy to fix in the code. It goes without saying I have the same issue. I am going to try to fix this myself and if I do I will send you the fix.

**Comment by dagochen** [comment]
ok
