### ISSUE TITLE
Not casting buff on correct player

### ISSUE THREAD

**Issue by gotmilk0112** [dagochen/RABuff#4]
For some reason, when I click one of the bars to cast a buff, it does not cast on the player who needs it, it just keeps casting on myself over and over.

Even if I have that player targeted, it still casts the buff on me instead, even though I already have it.

**Comment by dagochen** [comment]
selfcast enabled/disabled?

**Comment by gotmilk0112** [comment]
Hm, yeah, it does work fine when I disable self-cast.

Is there any way to get around that? I kinda have 8+ years of being used to having auto self-cast, heh.

**Comment by dagochen** [comment]
I dont think so.
